ignore:
  - "src/main/java/io/github/nikmang/shserver/SHServer.java"
  - "src/main/java/io/github/nikmang/shserver/User.java"
  - "src/main/java/io/github/nikmang/shserver/handlers/commands/Invalid.java"